from .auth            import auth_bp
from .dashboard       import dashboard_bp
from .meeting         import meeting_bp
from .attendance      import attendance_bp
from .payroll         import payroll_bp
from .task            import task_bp
from .employee        import employee_bp
from .leave           import leave_bp
from .admin_approval  import admin_approval_bp
